# Generated by Django 5.0.6 on 2024-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=250)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Product',
                'db_table': 'Product_table',
            },
        ),
    ]
